/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to follow project patterns (PieceMaterial, ModelProps)
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/k9-16bb4f352e714c50b6fd5f11e0ed60c5
Title: K9
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import { PieceMaterial, ModelProps } from './index'

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.Mesh
    Object_4: THREE.Mesh
    Object_21: THREE.Mesh
    Object_33: THREE.Mesh
    Object_90: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    Collar: THREE.MeshStandardMaterial
  }
}

export const K9Model: React.FC<ModelProps> = (props) => {
  const { nodes } = useGLTF('/k9.glb') as unknown as GLTFResult
  const { color, isSelected, pieceIsBeingReplaced } = props
  const materialProps = { color, isSelected, pieceIsBeingReplaced }

  // Black pieces need to face the opposite direction
  // K-9 model has a slight rotation offset (~0.844 rad) that we need to counter
  // Added 135° CW rotation (-3π/4 radians) per user request
  const baseRotation = -0.844 - (3 * Math.PI / 4) // Counter built-in rotation + 135° CW
  const yRotation = color === 'black' ? baseRotation + Math.PI : baseRotation

  return (
    <group dispose={null} scale={250} rotation={[0, yRotation, 0]}>
      <group position={[-0.048, 0, 0.022]}>
        <group position={[-0.001, -0.001, 0]}>
          <mesh geometry={nodes.Object_9.geometry}>
            <PieceMaterial {...materialProps} />
          </mesh>
        </group>
        <mesh geometry={nodes.Object_4.geometry}>
          <PieceMaterial {...materialProps} />
        </mesh>
        <mesh geometry={nodes.Object_21.geometry}>
          <PieceMaterial {...materialProps} />
        </mesh>
        <mesh geometry={nodes.Object_33.geometry} position={[0, 0.015, 0]}>
          <PieceMaterial {...materialProps} />
        </mesh>
        <mesh geometry={nodes.Object_90.geometry} position={[0.003, 0.004, 0.003]}>
          <PieceMaterial {...materialProps} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/k9.glb')
